### PR TITLE
Simplified characters for group 1433

### PR DESCRIPTION
**Pull request by paulmasson**
These characters do not appear in Casey.

### CODE REVIEW

**Comment by kenlunde** [comment]
GitHub is reporting conflicts in this PR. I merged the PRs in sequence, so the issue is not on my side.

**Comment by kenlunde** [comment]
GitHub is still reporting conflicts. 🤷

**Comment by paulmasson** [comment]
Try now

**Comment by kenlunde** [comment]
Now GitHub states that the branch cannot be rebased due to conflicts.

**Comment by paulmasson** [comment]
Will redo the PR tomorrow

**Comment by kenlunde** [comment]
Speaking of tomorrow, if you can hold off on any **new** PRs during the coming week, it would be appreciated. I am attending the ISO WG2 meeting this coming week, and because I am remote, I am waking up before 4AM to attend the afternoon session, and have my day job on top of that later in the day. I am therefore sleeping earlier than usual this week. I am also driving to South Dakota this coming weekend.

**Comment by paulmasson** [comment]
Not a problem

**Pull request closed without merging**
