### PR TITLE
Additions for group 1432

### PR DESCRIPTION
**Pull request by paulmasson**
These characters do not appear in Casey.

### CODE REVIEW

**Comment by kenlunde** [comment]
I merged the PRs in the order that they came in, yet for this one, GitHub states that the branch has conflicts. The PR that came after this one has no such conflicts.

**Comment by paulmasson** [comment]
@kenlunde try again

**Comment by kenlunde** [comment]
No dice: `This branch cannot be rebased due to conflicts`

**Comment by paulmasson** [comment]
The merge conflicts are occurring because the region above U+20000 is relatively sparsely populated in this file, making it more likely that sequential pull requests will try to add adjacent lines in this region. I’ve removed the line in question, so there should be no conflict in the total commit.

Perhaps the error you’re seeing is from performing a standard merge which tries to apply each individual commit in turn. Can you try a squash and merge instead?

**Comment by kenlunde** [comment]
Will try…

**Comment by kenlunde** [comment]
That seemed to have worked.

**Pull request merged**
