### PR TITLE
Reassignments for group 1236

### PR DESCRIPTION
**Pull request by paulmasson**

### CODE REVIEW

**Comment by kenlunde** [comment]
I see conflicts with this PR.

**Comment by paulmasson** [comment]
@kenlunde the conflict results from modifying an line adjacent to the last pull request. Git apparently cannot resolve changes to adjacent lines. Should be fixed now.

**Comment by kenlunde** [comment]
I am now seeing a different message that actually seems worse: `This branch cannot be rebased due to conflicts`

**Comment by paulmasson** [comment]
@kenlunde  that could be because you merged another PR before this one. I'll just redo this one tomorrow.

**Comment by kenlunde** [comment]
I don't think so. I have been merging PRs in the order that they have been posted. I merged the newer one a few minutes ago, because when I first checked this one, it gave me the message that I mentioned above. Maybe I should simply apply the changes on my end, push the result, then close this PR.

**Comment by paulmasson** [comment]
Replaced by #92

**Pull request closed without merging**
