### PR TITLE
Additions for group 810

### PR DESCRIPTION
**Pull request by paulmasson**
These characters do not appear in Casey.

There is probably a merge conflict here...

### CODE REVIEW

**Comment by paulmasson** [comment]
Squash and merge, please!

**Comment by kenlunde** [comment]
The issue may have been with U+45C3, not with U+45C0.

**Comment by kenlunde** [comment]
God, I hate Git.

**Comment by paulmasson** [comment]
The two characters were on adjacent lines. Git gets confused in such a circumstance. Thanks for your patience!

**Pull request merged**
